In [1]:
import numpy as np
import matplotlib.pyplot as plt

n=10
np.random.seed(69)
island = np.random.randint(2, size=(n, n))
print(island)

def checknum(input1,num):
    x = input1.shape[0]
    y = input1.shape[1]
    numofnums = 0
    
    for i in range(0,x):
        for j in range(0,y):
            if input1[i,j] == num:
                numofnums += numofnums
                return 1
                break
    if numofnums == 0:
        return 0

def islandnum(input2):
    islandnum = 2
    while (checknum(input2,1) == 1):
        for i in range(0,input2.shape[0]):
            for j in range(0,input2.shape[1]):
                if input2[i,j] == 1:
                    input2[i,j] = islandnum
                    if i+1 <= n-1:
                        if input2[i+1,j] == 1:
                            input2[i+1,j] = -1
                    if j+1 <= n-1:
                        if input2[i,j+1] == 1:
                            input2[i,j+1] = -1
                    if j-1 >= 0:
                        if input2[i,j-1] == 1:
                            input2[i,j-1] = -1
                    if i-1 >= 0:
                        if input2[i-1,j] == 1:
                            input2[i-1,j] = -1
                    
                    while(checknum(input2,-1) == 1):
                        for ii in range(0,input2.shape[0]):
                            for jj in range(0,input2.shape[1]):
                                if input2[ii,jj] == -1:
                                    input2[ii,jj] = islandnum
                                    if ii+1 <= n-1:
                                        if input2[ii+1,jj] == 1:
                                            input2[ii+1,jj] = -1
                                    if jj+1 <= n-1:
                                        if input2[ii,jj+1] == 1:
                                            input2[ii,jj+1] = -1
                                    if jj-1 >= 0:
                                        if input2[ii,jj-1] == 1:
                                            input2[ii,jj-1] = -1
                                    if ii-1 >= 0:
                                        if input2[ii-1,jj] == 1:
                                            input2[ii-1,jj] = -1
                    if checknum(input2,-1) == 0:
                        islandnum = islandnum + 1
                        
    islandnum = islandnum-2
    return islandnum

def islandsize(input3,num2):
    islandsize = np.arange(num2)*0
    for k in range(2,2+num2):
        for i in range(0,input3.shape[0]):
            for j in range(0,input3.shape[1]):
                if input3[i,j] == k:
                    islandsize[k-2] = islandsize[k-2] + 1
    
    return islandsize


                      
a = islandnum(island)                  
b = islandsize(island,a)

for x in range(a):
    print('island',x+1,'size =',b[x])

[[0 1 1 1 0 1 0 1 0 1]
 [0 1 0 0 0 0 1 0 0 1]
 [1 1 0 1 0 0 1 1 0 0]
 [1 1 0 1 0 1 1 1 0 0]
 [1 1 0 1 0 0 0 1 0 1]
 [1 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 0 1 1]
 [1 1 1 0 0 1 0 0 1 0]
 [1 1 0 1 1 1 0 1 1 1]]
island 1 size = 13
island 2 size = 1
island 3 size = 1
island 4 size = 2
island 5 size = 8
island 6 size = 4
island 7 size = 2
island 8 size = 1
island 9 size = 1
island 10 size = 1
island 11 size = 1
island 12 size = 7
island 13 size = 6
island 14 size = 1
island 15 size = 5
